### ISSUE TITLE
[FEATURE] Link Grafana up to Keycloak OpenID plugin to show Grafana on EKS

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#105]
**Is your feature request related to a problem? Please describe.**
We need to link up auth within Keycloak to allow access to the info in Grafana on health of the system. 

**Describe the solution you'd like**
We need to have a new realm within Keycloak for openrmf-grafana that can house users for logging into the application. Right now just Dave, Nick, and myself.

**Additional context**
Goes with #60

**Comment by Cingulara** [comment]
https://grafana.com/docs/grafana/latest/installation/configuration/#auth-generic-oauth

**Comment by Cingulara** [comment]
Not leaving this up, but it will be something like this in the Grafana YAML area of the Prometheus Operator:

```
    grafana.ini:
      log:
        mode: console
      server:
        root_url: "https://xxxxxxxxxxxxxxxxxxx.openrmf.io/"
        auth.generic_oauth:
        enabled: true
        name: "Oauth"
        allow_sign_up: false
        client_id: "xxxxxxxxxxxxxx"
        # scopes = user:email,read:org
        client_secret: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        auth_url: "http://keycloak.openrmf.io/auth/realms/xxxxx/protocol/openid-connect/auth"
        token_url: "http://keycloak.openrmf.io/auth/realms/xxxxx/protocol/openid-connect/token"
        api_url: "http://keycloak.openrmf.io/auth/realms/xxxxx/protocol/openid-connect/userinfo"
```
