### ISSUE TITLE
[FEATURE] Update all build workflows to use .net 6

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#287]
**Is your feature request related to a problem? Please describe.**
Update the build workflows to do testing and creation based on .net 6 when we update to that. 

**Describe the solution you'd like**
Add this to the workflow YML files

```
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
